services:
  database:
    image:  neo4j:latest
    container_name: database
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    volumes:
      - ./db:/data
      - ./logs:/logs
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/ivanivan
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]